<a href="https://colab.research.google.com/github/markcastor/Machine-Learning-Deeplearning/blob/main/torch_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)


cuda


In [3]:
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())

2.0.1+cu118
11.8
8700


In [4]:
import numpy as np
import time


In [5]:
%%time
start_time = time.time()
# matrix ooperations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.02742267
CPU times: user 1.87 ms, sys: 306 µs, total: 2.18 ms
Wall time: 27.6 ms


In [6]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to (device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elasped_time = end_time - start_time
print(f"{elasped_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elasped_time = end_time - start_time
print(f"{elasped_time:.8f}")

2.61081195
0.15021324


In [7]:
#Defineing a probability tensor
probabilities = torch.tensor([0.1, 0.9])
#10% or 0.1 => 0 , 90% or 0.9 => 1. each probability in the tensor
#Now draw 5 samples from multinormal distribution

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 1, 1, 1, 1, 0, 1, 1])


In [8]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor,torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [9]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [11]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [12]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [13]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [14]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

#Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
import torch.nn as nn
sample = torch.tensor([10.,10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 0.3892, -5.3587,  1.9922], grad_fn=<SqueezeBackward4>)


In [16]:
import torch.nn.functional as  F

##Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


Embedding vectors

In [17]:
 #initialize an embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

#create some input indices
input_indices = torch.LongTensor([1,5,3,2])


#Apply the emedding layer
embedded_output = embedding(input_indices)

#Now the output will then be a tensor pf shape (4, 100), where 4 is the number of input and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)


torch.Size([4, 100])
tensor([[-0.8712,  1.1694,  0.1480, -1.2960,  1.1343,  2.0926,  1.0733, -0.8705,
          0.2983,  0.5363,  0.4623,  1.0320,  0.6385, -0.7507, -1.1382,  0.4717,
          0.4806, -0.7453, -0.8444,  0.9301,  0.9545,  0.3083,  0.2727,  0.4105,
          0.5760, -0.5359,  1.3096, -0.4366, -0.7101, -1.0031, -2.1746,  0.6787,
          0.0136, -0.5456, -0.2620,  0.2744,  0.3842,  1.4577, -0.7543,  1.4456,
         -2.0633, -0.4963, -0.6274, -1.0092,  0.3690, -0.2546, -0.7235,  0.8127,
          0.2000, -1.0976,  0.6983,  0.7781,  1.4609, -1.8887, -1.5463, -0.0558,
         -1.1834,  1.6290,  0.3123, -0.2729, -0.4106,  0.0419,  1.0105,  0.7741,
          1.2489,  0.4359, -1.3470,  1.1164, -1.8804, -0.4446,  0.0944, -1.5564,
          0.0411, -0.1318,  0.6047, -0.0118, -0.7806,  0.4455,  0.6887, -0.9780,
          0.5877, -0.4413, -0.2724, -0.3535,  1.1603,  2.6236,  0.6197,  0.5271,
          0.7114,  0.6738, -1.3735, -1.0671,  0.5636,  0.3748, -0.0687,  2.1835,
       

In [19]:
a = torch.tensor([[1,2],[3,4], [5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(torch.matmul (a , b))



tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [28]:
int_64 = torch.randint(1, 10, size=(3, 2)).float()  # Explicitly specify int64
float_32 = torch.rand(2, 3)               # Explicitly specify float32
result = torch.matmul(int_64, float_32)
print(result)

tensor([[6.8839, 4.2168, 8.8085],
        [6.4144, 2.2531, 6.9945],
        [4.6675, 3.1385, 6.1747]])
